#TLB-DOC-START@test::unit-rake-task@
require 'rake'
require 'rubygems'
if RUBY_VERSION =~ /^1\.9/
  gem 'tlb-testunit19'
else
  gem 'tlb-testunit18'
end
require 'tlb/test_unit/test_task'

Tlb::TestUnit::TestTask.new(:test_balanced) do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

load 'tasks/tlb.rake'

task :bal => ['tlb:start', :test_balanced]
#TLB-DOC-END@test::unit-rake-task@

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

