require 'rake'
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

require 'rubygems'
gem 'tlb-testunit'
require 'tlb'
require 'tlb/test_unit/test_task'

Tlb::TestUnit::TestTask.new(:test_balanced) do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

load 'tasks/tlb.rake'

task :bal => ['tlb:start', :test_balanced]
