#TLB-DOC-START@rspec2-rake-task@
#Use the task :bal to run balanced test suite. You can change the t.pattern to match whatever tests you need
#to run.
require 'rubygems'
gem 'tlb-rspec2'
require 'tlb/rspec/spec_task'

Tlb::RSpec::SpecTask.new(:run_balanced) do |t|
  t.pattern = 'spec/**/*_spec.rb'
  #t.tlb_module_name = 'my-rspec-module'
  #NOTE: Comment out previous line if your project has multiple modules(or test modules) each having its own test task. Set module name appropriately for each test-task in a multiple-module setup.
  #You can verify that all partitions executed by invoking `tlb_module_name='my-rspec-module,other-module' rake tlb:ensure_all_partitions_executed` (where environment variable 'tlb_module_name' is set to comma seperated list of all/some module names).
end

load 'tasks/tlb.rake'
desc "run specs load-balanced(based on environment variables)"
task :bal => ['tlb:start', :run_balanced]
#TLB-DOC-END@rspec2-rake-task@

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = 'spec/**/*_spec.rb'
end
