require 'rake'
require 'rubygems'
require 'spec/rake/spectask'

Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
end

gem 'tlb-rspec1'
require 'tlb'
require 'tlb/spec_task'

Tlb::SpecTask.new(:run_balanced) do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.spec_opts << '--format progress'
end

load 'tasks/tlb.rake'

task :bal => ['tlb:start', :run_balanced]


