#TLB-DOC-START@rspec1-rake-task@
#Use the task :bal to run balanced test suite. You can change the FileSet to match whatever tests you need
#to run.
require 'rubygems'
gem 'tlb-rspec1'
require 'tlb/spec/spec_task'

Tlb::SpecTask.new(:balanced_specs) do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.spec_opts << "--format progress"
  #t.tlb_module_name = 'my-spec-module'
  #NOTE: Comment out previous line if your project has multiple modules(or test modules) each having its own test task. Set module name appropriately for each test-task in a multiple-module setup.
  #You can verify that all partitions executed by invoking `tlb_module_name='my-spec-module' rake tlb:ensure_all_partitions_executed` (where environment variable 'tlb_module_name' is set to comma seperated list of all/some module names).
end

load 'tasks/tlb.rake'
desc "run specs load-balanced(based on environment variables)"
task :bal => ['tlb:start', :balanced_specs]
#TLB-DOC-END@rspec1-rake-task@

require 'spec/rake/spectask'

Spec::Rake::SpecTask.new(:spec) do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
end

